"""
RadioAI — Final Log Creator (Figma 64:2). Phase F4 + Phase F-Final S5.

Pre-computes the 24-hour broadcast plan for the active date by walking
auto_schedule (with force_clocks override) and dispatching each clock
slot through the scheduler's pickers. Each generated entry is stored in
final_log_entries. The Phase E AI integration replaces the deterministic
generator with a Claude-driven one that also rewrites copy + voice
tracks; this S5 implementation lays the table-shape + UI flow.

Layout (1440 × 900):
  HEADER     1440 ×  72   y=  0..72
  CONTENT    1440 × 792   y= 72..864
    LEFT      240 × 792    — Generate Log controls
    CENTER    832 × 792    — log preview list
    RIGHT     368 × 792    — Log Actions + AI Warnings
  STATUSBAR  1440 ×  36
"""

from __future__ import annotations

import logging
from typing import Optional

from PyQt6.QtCore import Qt, pyqtSignal
from PyQt6.QtGui import QCursor, QFont
from PyQt6.QtWidgets import (
    QWidget, QFrame, QLabel, QPushButton, QVBoxLayout, QHBoxLayout,
    QListWidget, QListWidgetItem, QMessageBox,
)

from ui.widgets._phase_stub import StubHeader, StubStatusBar, BORDER
from ui.widgets._tokens import (
    inter, mono, rgba,
    BG_BASE, BG_DARK, BG_PANEL, BG_CARD, BG_CARD_DK,
    TEXT_PRI, TEXT_SEC, TEXT_MUTED, TEXT_DIM,
    CYAN, CYAN_LIGHT, PURPLE, PURPLE_LIGHT,
    GREEN, GREEN_LIGHT, AMBER, AMBER_LIGHT, RED, RED_LIGHT, PINK,
)

log = logging.getLogger("FinalLog")

WINDOW_W = 1440; WINDOW_H = 900
HEADER_H = 72; STATUS_H = 36
LEFT_W = 240; RIGHT_W = 368
CENTER_W = WINDOW_W - LEFT_W - RIGHT_W
CONTENT_Y = HEADER_H
CONTENT_H = WINDOW_H - HEADER_H - STATUS_H


class FinalLog(QWidget):
    breadcrumb_clicked = pyqtSignal(str)
    studio_clicked     = pyqtSignal()

    def __init__(self, db, parent=None, scheduler=None):
        super().__init__(parent)
        self._db = db
        self._scheduler = scheduler
        self.setFixedSize(WINDOW_W, WINDOW_H)
        self.setStyleSheet(f"QWidget {{ background: {BG_BASE}; }}")

        h = StubHeader("Final Log", "Final Log Creator",
                       active_color=GREEN_LIGHT, parent=self)
        h.setGeometry(0, 0, WINDOW_W, HEADER_H)
        h.control_panel_clicked.connect(
            lambda: self.breadcrumb_clicked.emit("control_panel"))
        h.scheduling_clicked.connect(
            lambda: self.breadcrumb_clicked.emit("scheduling_hub"))
        h.studio_clicked.connect(self.studio_clicked.emit)

        # Left — Generate Log
        left = QFrame(self)
        left.setGeometry(0, CONTENT_Y, LEFT_W, CONTENT_H)
        left.setStyleSheet(
            f"QFrame {{ background: {BG_DARK}; "
            f"border-right: 1px solid {BORDER}; }}"
        )
        lv = QVBoxLayout(left); lv.setContentsMargins(12, 14, 12, 14); lv.setSpacing(10)
        lv.addWidget(self._section("GENERATE LOG", GREEN_LIGHT))
        lv.addWidget(self._option_pill("Today", active=True))
        lv.addWidget(self._option_pill("Tomorrow"))
        lv.addWidget(self._option_pill("7 Days"))
        lv.addWidget(self._option_pill("Custom"))
        lv.addSpacing(6)
        lv.addWidget(self._section("Generation Mode", TEXT_MUTED))
        lv.addWidget(self._option_pill("✦ AI Auto-Generate", color=PURPLE_LIGHT, active=True))
        lv.addWidget(self._option_pill("From Clock Rules", color=CYAN_LIGHT))
        lv.addWidget(self._option_pill("Manual Build", color=AMBER))
        lv.addStretch()
        gen_btn = self._action_btn("▶ Generate Log Now", GREEN_LIGHT, big=True)
        gen_btn.clicked.connect(self._on_generate_stub)
        lv.addWidget(gen_btn)
        lv.addWidget(self._action_btn("✦ AI Magic — Full Auto", PURPLE_LIGHT))
        lv.addWidget(self._action_btn("✓ View Saved Logs", CYAN_LIGHT))

        # Center — log preview
        center = QFrame(self)
        center.setGeometry(LEFT_W, CONTENT_Y, CENTER_W, CONTENT_H)
        center.setStyleSheet(
            f"QFrame {{ background: {BG_BASE}; "
            f"border-right: 1px solid {BORDER}; }}"
        )
        cv = QVBoxLayout(center); cv.setContentsMargins(20, 14, 20, 14); cv.setSpacing(8)
        from datetime import datetime
        title = QLabel(f"FINAL LOG — {datetime.now().strftime('%A %d %B %Y')}")
        title.setFont(inter(13, QFont.Weight.Black, letter_spacing=0.6))
        title.setStyleSheet(f"color: {TEXT_PRI}; background: transparent;")
        cv.addWidget(title)
        sub = QLabel("Generated by AI · — entries · 24:00:00 · Last modified: —")
        sub.setFont(inter(9))
        sub.setStyleSheet(f"color: {TEXT_MUTED}; background: transparent;")
        cv.addWidget(sub)

        # Filter tabs
        tabs = QHBoxLayout(); tabs.setSpacing(6)
        for label, color in [("All", CYAN_LIGHT), ("Songs", AMBER),
                             ("Spots", PINK), ("Jingles", PURPLE_LIGHT),
                             ("Breaks", GREEN)]:
            b = QPushButton(label); b.setFixedHeight(26)
            b.setFont(inter(9, QFont.Weight.DemiBold))
            b.setStyleSheet(self._tab_qss(color, label == "All"))
            tabs.addWidget(b)
        tabs.addStretch()
        cv.addLayout(tabs)

        # Log entries list — populated from final_log_entries
        self._log_list = QListWidget()
        self._log_list.setStyleSheet(
            f"QListWidget {{ background: {BG_CARD_DK}; "
            f"color: {TEXT_PRI}; "
            f"border: 1px solid {BORDER}; "
            f"border-radius: 6px; padding: 4px; }}"
            f"QListWidget::item {{ padding: 4px; }}"
        )
        cv.addWidget(self._log_list, 1)
        self._title_label = title
        self._sub_label = sub
        self._refresh_log_view()

        # Right — Log Actions
        right = QFrame(self)
        right.setGeometry(LEFT_W + CENTER_W, CONTENT_Y, RIGHT_W, CONTENT_H)
        right.setStyleSheet(f"QFrame {{ background: {BG_PANEL}; }}")
        rv = QVBoxLayout(right); rv.setContentsMargins(14, 14, 14, 14); rv.setSpacing(8)
        rv.addWidget(self._section("LOG ACTIONS", PURPLE_LIGHT))
        for label, color in [("✓ Confirm & Lock Log", GREEN_LIGHT),
                             ("📥 Export as Text File", CYAN_LIGHT),
                             ("🖨 Print Log", PURPLE_LIGHT),
                             ("↻ Regenerate Log", AMBER),
                             ("✎ Edit Entry", PURPLE_LIGHT),
                             ("✗ Delete Entry", RED_LIGHT),
                             ("🔒 Lock Entry", GREEN_LIGHT)]:
            rv.addWidget(self._action_btn(label, color))
        rv.addStretch()
        rv.addWidget(self._section("AI WARNINGS", AMBER))
        warn = QLabel("Run a Generate Log first — AI warnings need a draft.")
        warn.setFont(inter(9)); warn.setWordWrap(True)
        warn.setStyleSheet(f"color: {TEXT_MUTED}; background: transparent;")
        rv.addWidget(warn)

        sb = StubStatusBar("Final Log Creator", parent=self)
        sb.setGeometry(0, WINDOW_H - STATUS_H, WINDOW_W, STATUS_H)

        log.info("FinalLog ready (Figma 64:2)")

    # ── helpers ───────────────────────────────────────────────────────────

    def _section(self, text: str, color: str) -> QLabel:
        lbl = QLabel(text)
        lbl.setFont(inter(8, QFont.Weight.Black, letter_spacing=1.6))
        lbl.setStyleSheet(f"color: {color}; background: transparent;")
        return lbl

    def _option_pill(self, text: str, color: str = CYAN_LIGHT,
                     active: bool = False) -> QFrame:
        f = QFrame(); f.setFixedHeight(28)
        bg = rgba(color, 0.18) if active else BG_CARD_DK
        bd = rgba(color, 0.40) if active else BORDER
        f.setStyleSheet(
            f"QFrame {{ background: {bg}; "
            f"border: 1px solid {bd}; border-radius: 4px; }}"
        )
        h = QHBoxLayout(f); h.setContentsMargins(8, 0, 8, 0); h.setSpacing(0)
        l = QLabel(text); l.setFont(inter(9, QFont.Weight.DemiBold))
        l.setStyleSheet(f"color: {color if active else TEXT_SEC}; "
                        f"background: transparent;")
        h.addWidget(l)
        return f

    def _action_btn(self, label: str, color: str, big: bool = False) -> QPushButton:
        b = QPushButton(label)
        b.setFixedHeight(36 if big else 28)
        b.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        b.setFont(inter(11 if big else 10, QFont.Weight.Bold if big else QFont.Weight.DemiBold))
        b.setStyleSheet(
            f"QPushButton {{ background: {rgba(color, 0.18 if not big else 0.24)}; "
            f"color: {color}; "
            f"border: 1px solid {rgba(color, 0.40)}; "
            f"border-radius: 5px; padding: 0 12px; text-align: left; }}"
            f"QPushButton:hover {{ background: {rgba(color, 0.30)}; }}"
        )
        return b

    def _tab_qss(self, color: str, active: bool) -> str:
        if active:
            return (
                f"QPushButton {{ background: {rgba(color, 0.20)}; "
                f"color: {color}; "
                f"border: 1px solid {rgba(color, 0.40)}; "
                f"border-radius: 4px; padding: 0 12px; }}"
            )
        return (
            f"QPushButton {{ background: transparent; "
            f"color: {TEXT_SEC}; "
            f"border: 1px solid {BORDER}; "
            f"border-radius: 4px; padding: 0 12px; }}"
            f"QPushButton:hover {{ color: {TEXT_PRI}; }}"
        )

    def _refresh_log_view(self) -> None:
        """Pull the current date's final_log + entries and rebuild the
        center list. Updates the title block to show entry/break/duration
        summary."""
        from datetime import datetime
        date_str = datetime.now().strftime("%Y-%m-%d")
        log_row = self._db.get_final_log(date_str)
        self._log_list.clear()
        if log_row is None:
            self._log_list.addItem(QListWidgetItem(
                "  No log generated yet for today. Click ‘Generate Log "
                "Now’ to compose one from your clocks + auto_schedule."))
            self._sub_label.setText(
                "Generated by AI · — entries · 24:00:00 · Last modified: —")
            return
        entries = list(self._db.get_final_log_entries(int(log_row["id"])))
        n = len(entries)
        total_ms = sum(int(e["duration_ms"] or 0) for e in entries)
        # Format hh:mm:ss
        ts = total_ms // 1000
        hh, rem = divmod(ts, 3600); mm, ss = divmod(rem, 60)
        self._sub_label.setText(
            f"Generated by AI · {n} entries · {hh:02d}:{mm:02d}:{ss:02d} "
            f"· Last modified: {log_row['generated_at']}")
        if not entries:
            self._log_list.addItem(QListWidgetItem(
                "  Log row exists but has no entries — try Regenerate."))
            return
        for e in entries:
            time_part = (e["scheduled_time"] or "—:—:—")
            etype = (e["entry_type"] or "—").upper()
            artist = e["artist_override"] or "—"
            title = e["title_override"] or "—"
            self._log_list.addItem(QListWidgetItem(
                f"  {time_part}   {etype:<11}  {artist:<28} {title}"))

    def _on_generate_stub(self):
        """S5: real generation. Walks the day, dispatches each slot
        through the scheduler's pickers, persists final_log_entries."""
        from datetime import datetime
        if self._scheduler is None:
            # Lazy-construct a scheduler instance just for generation
            # (its DB is the same one we already hold).
            from core.scheduler.engine import SchedulerEngine
            sch = SchedulerEngine(db=self._db)
        else:
            sch = self._scheduler
        date_str = datetime.now().strftime("%Y-%m-%d")
        try:
            result = self._db.generate_final_log(date_str, sch)
        except Exception as exc:
            log.warning(f"generate_final_log failed: {exc}")
            QMessageBox.warning(self, "Generate failed", str(exc))
            return
        QMessageBox.information(
            self, "Log Generated",
            f"Final log generated for {date_str}.\n\n"
            f"{result['entry_count']} entries · "
            f"{result['hours_resolved']} hours resolved · "
            f"{result['hours_empty']} hours empty · "
            f"{result['warning_count']} warnings.")
        self._refresh_log_view()
